---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - name: Install packages
      apt:
        name:
          - htop
          - vim
          - xclip
          - tmux
          - python3-psutil
          - tree
          - flatpak

    - include: tasks/gnome.yml
    - include: tasks/conda.yml
    - include: tasks/flatpak.yml 
    - include: tasks/docker.yml
    - include: tasks/ssh.yml
    - include: tasks/brave.yml
    - include: tasks/snx.yml
