---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    # - include: tasks/users.yml
    - name: Install packages
      apt: name={{item}}
      with_items:
        - htop
        - tmux
        - psutils
    - include: gnome.yml
    - include: conda.yml
    - include: docker.yml
