---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - name: Install packages
      apt:
        name:
          - htop
          - tmux
          - psutils
          - tree 

    - include: gnome.yml
    - include: conda.yml
    - include: flatpak.yml 
    - include: docker.yml
